### ISSUE TITLE
Increase compression level

### ISSUE THREAD

**Issue by Smoozilla** [main--/rust-lz-fear#14]
Hello and thank you for this project.

The speed is incredible though if possible I'd like to trade some of that speed for a better compression ratio. How can I do this?

Thanks again!

**Comment by milesgranger** [comment]
Can we re-open this? Maybe I'm reading it wrong, but [according to the docs](https://docs.rs/lz-fear/0.1.1/lz_fear/framed/struct.CompressionSettings.html) I can't see where the API enables controlling the compression level.

**Comment by Smoozilla** [comment]
Hi @milesgranger 

I am not certain but I believe that compression setting only comes with lz4hc and not plain lz4. I could me mistaken but this is why I closed it.

I can reopen so we can get some clarification,

Thanks

**Comment by main--** [comment]
Sorry for the late response. As you correctly observed, the LZ4 command line utility's compression options essentially only apply to lz4hc. The basic algorithm that is currently implemented here is not really tuneable (aside from maybe tweaking dictionary size or something like that).

The idea was that the crate could at some point offer other algorithms as well, i.e. LZ4-HC and even advanced variants like https://github.com/stbrumme/smallz4 but so far none of that is implemented. Contributions are always appreciated though!
